// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"rbac-opa-server-mariadb/app/controller"
	"rbac-opa-server-mariadb/app/repository"
	"rbac-opa-server-mariadb/app/service"
)

// Injectors from wire.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	dataRepositoryImpl := repository.DataRepositoryInit(gormDB)
	apiServiceImpl := service.ApiServiceInit(dataRepositoryImpl)
	apiControllerImpl := controller.ApiControllerInit(apiServiceImpl)
	initialization := NewInitialization(apiControllerImpl, apiServiceImpl, dataRepositoryImpl)
	return initialization
}

// wire.go:

var db = wire.NewSet(ConnectToDB)

var apiCtrlSet = wire.NewSet(controller.ApiControllerInit, wire.Bind(
	new(controller.ApiController),
	new(*controller.ApiControllerImpl),
))

var apiSvcSet = wire.NewSet(service.ApiServiceInit, wire.Bind(
	new(service.ApiService),
	new(*service.ApiServiceImpl),
))

var dataRepoSet = wire.NewSet(repository.DataRepositoryInit, wire.Bind(
	new(repository.DataRepository),
	new(*repository.DataRepositoryImpl),
))
